/**:
  ros__parameters:
    param_name: 789
    # build_engine: false
    show_image: true
    model_path: "/home/wydl/Projects/src/cones_detect/src/best_nano.onnx"
    # engine_path: "src/universe/external/cones_detect/src/best_nano.engine"